package com.epam.jmp.model;

public enum EmployeeStatus {

	PROGRAMMER, TESTER, CLEANER, HR, TRAINER, TEAM_LEADER, TEST_LEADER, RESOURCE_MANAGER, PROJECT_MANAGER, 
	DEVELOPMENT_MANAGER, ARCHITECTOR, DB_MANAGER, UNIT_COORDINATOR, DIRECTOR, STAFF
}
